default: &default
  adapter: <%= ENV['database_adapter'] %>
  pool:    <%= ENV['database_pool'] %>
  database: <%= ENV['database_name'] %>
  encoding: <%= ENV['database_encoding'] %>

development:
  <<: *default

test:
  <<: *default
  database: bank_management_test

production:
  <<: *default
